models:
  - name: gemma3_4b
    ollama_model: gemma3:4b

  - name: qwen3_4b
    ollama_model: qwen3:4b

  - name: qwen3_8b
    ollama_model: qwen3:8b

  - name: gemma4_12b
    ollama_model: gemma4:12b
